### ISSUE TITLE
Github check show pass only when all or Hydras build and tests pass

### ISSUE THREAD

**Issue by zo-el** [Holo-Host/holo-nixpkgs#1177]
Currently, GitHub check represents only the holo-nixpkgs build. We need to show if all the tests on holo-nixpkgs pass or any other build fails.

This is so that we can block PR from being merged into develop or master when there is something failing to build 

Proof: 
This is the state of hydra that shows one build fail: https://hydra.holo.host/eval/2269515
This is the checkmark on github for that same commit:  https://github.com/Holo-Host/holo-nixpkgs/commit/2f81419e7031e4d917aea9e2e7c0026a959287f9

**Comment by peeech** [comment]
This issue has been identified in a [#28](https://github.com/Holo-Host/bugs-n-issues/issues/28) and fixed in [PR #1092](https://github.com/Holo-Host/holo-nixpkgs/pull/1092). The reason you are still seeing this happen is that the code which is fixing this issue needs to be merged into a PR, for example by rebasing your branch onto latest develop

**Comment by peeech** [comment]
What you are seeing was observed by @cole-h in [this](https://github.com/Holo-Host/bugs-n-issues/issues/35#issuecomment-1064414824) comment. Basically the code was merged into Hydra and never made it to develop. PR #1183 is fixing it.
