### ISSUE TITLE
Add additional logging to hpos-admin

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-nixpkgs#388]
Currently `hpos-admin` logs individual requests:

```
$ sudo ./result/bin/hpos-admin 
- - - [2020-02-21 17:48:13] "GET / HTTP/1.1" 404 341 0.017322
- - - [2020-02-21 17:48:23] "GET / HTTP/1.1" 404 341 0.000873
- - - [2020-02-21 17:48:24] "GET / HTTP/1.1" 404 341 0.001050
```

@peeech wants to add more logging. I wonder what exactly we should add? I guess we could print config value as it gets updated, but not sure if it makes sense to do so in production.

**Comment by peeech** [comment]
Good question. I think that cases like when CAS hash gets rejected or anything else that is abnormal for API functionality.

**Comment by alastairong** [comment]
This is the logging on the HoloPort itself not in browser right?

**Comment by yegortimoshenko** [comment]
Right.

**Comment by alastairong** [comment]
Don't know how helpful this is on the implementation level but since the API itself is relatively simple making it more human-readable for our tier 2 folks that would be great.

So for `PUT /v1/config` some examples might be:
`400 - bad response`
- Missing data
- Data in invalid format
- Invalid field
- Field is write only

`401 Unauthorized`
- Missing verified signature (or whatever is the right term)
- Wrong signature?

For `POST /v1/upgrade`
`400 Bad Request`
- An issue with the payload content?
- auto-upgrade.service failed to start
- Some other logging about auto-upgrade service status

**Comment by peeech** [comment]
`401` is handled by a different process - `hp-admin-crypto-server`
I also think that such a granularity of error messaging would make sense as an error response  for an open API - consumed by wide audience. In our case it's only HP Admin UI that accesses API. Granular error logging would be quite an overkill.
